# -*- coding: utf-8 -*-

{
    "name": "e3k MACMÉTAL",
    "summary": "",
    "category": "Sales/Sales",
    "author": "e3k",
    "license": "Other proprietary",
    "website": "https://e3k.co",
    "version": "19.0.2",
    "depends": [
        'sale_purchase',
        'sale_pdf_quote_builder',
        'crm',
        'calendar',
        'stock',
        'helpdesk',
    ],
    "data": [
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/sale_pdf_quote_builder_data.xml',
        'views/res_config_settings_views.xml',
        'views/sale_portal_templates.xml',
        'views/sale_views.xml',
        'views/stock_quant_views.xml',
        'views/stock_move_line_views.xml',
        'views/calendar_views.xml',
        'views/stock_location_views.xml',
        'views/route_config.xml',
        'views/res_partner_views.xml',
        'views/product_template_views.xml',
        'views/purchase_order_views.xml',
        'views/helpdesk_ticket_views.xml',
        # 'views/ticket_product_type_views.xml',
        'views/stock_picking_views.xml',
        'views/stock_move_views.xml',
    ],
    'assets': {
        'web.assets_frontend_lazy': [
            'e3k_macmetal/static/src/signature_form/mac_signature_form.js',
            'e3k_macmetal/static/src/signature_form/mac_signature_form.xml',
        ],
        'web.assets_backend': [
            'e3k_macmetal/static/src/js/sale_pdf_quote_builder/keep_editable_on_confirm.js',
        ],
    },
    "images": [],
    "application": False,
    "installable": True,
    "auto_install": False,
    "pre_init_hook": "pre_init_check",
}
